name: New Devops Task
description: New Devops Task
title: "[DevOps]: "
labels: ["devops"]

body:

  - type: markdown
    attributes: 
      value: "## Categorize"

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      options:
        - enhancement
        - fix
        - refactor
        - document
        - configure

  - type: dropdown
    id: phase
    attributes:
      label: What phase of the DevOps cycle is this targeting
      options:
        - plan
        - code
        - build
        - test
        - release
        - deploy
        - monitor
        - document
        - collaborate

  - type: checkboxes
    id: components
    attributes:
      label: What Components are Effected?
      options:
        - label: dev container
        - label: code base
        - label: repo
        - label: github

  - type: checkboxes
    id: environments
    attributes:
      label: What Enviroments are Effected?
      options:
        - label: local
        - label: dev
        - label: prod

  - type: markdown
    attributes:
      value: "## Describe"

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please enter a description on the task

  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: Please enter a description on the problem

  - type: textarea
    id: maturity-goal
    attributes:
      label: Maturity Goals
      placeholder: Please enter a maturity goal for this task

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      value: |
        As a [User]
        I want [Functionality]
        When [Predicate]
        Then [Outcome]

  - type: textarea
    id: scenario-map
    attributes:
      label: Scenario Map
      value: |
        Scenario: [ScenarioDescription]
          Given [Context]
          When [Predicate]
          Then [Outcome]

  - type: textarea
    id: additional-requirments
    attributes:
      label: Additional Requirments
      placeholder: Please enter any additional requirments

  - type: markdown
    attributes:
      value: "## Plan"

  - type: textarea
    id: solution
    attributes:
      label: Solution
      placeholder: Please describe the solution
      
  - type: textarea
    id: sub-tasks
    attributes:
      label: Sub Tasks
      placeholder: Please a list of subtasks

  - type: markdown
    attributes:
      value: "## Additional Resources"
      
  - type: textarea
    id: notes-links
    attributes:
      label: Notes & links
